version: '3'
services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"